name: 9Hits_Power_Bot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Farming
        run: |
          # ডাউনলোড এবং সরাসরি এক্সট্রাক্ট (কোনো এরর ছাড়াই)
          curl -sL https://9hits.com/downloads/v3/9hits-viewer-linux-x64.tar.bz2 | tar -xj
          
          # ফোল্ডারের ভেতরে গিয়ে ফাইল পারমিশন দেওয়া
          cd 9hits-viewer-linux-x64
          chmod +x 9hits-viewer
          
          # আপনার সঠিক API Key দিয়ে সেশন রান করা
          # এখানে সেশন ২টা দেওয়া হয়েছে যাতে পয়েন্ট দ্রুত জমা হয়
          ./9hits-viewer --token=08aa8c374e5713f7a572bae472c75cc4 --allow-ca --session=s1 &
          ./9hits-viewer --token=08aa8c374e5713f7a572bae472c75cc4 --allow-ca --session=s2
          
          # বটের কাজ সচল রাখার জন্য সময়সীমা (প্রায় ৬ ঘণ্টা)
          sleep 21000
