name: 9Hits_Power_Bot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing and Running
        run: |
          # সব লাইব্রেরি একসাথে ইনস্টল
          sudo apt-get update && sudo apt-get install -y libnss3 libgbm1 libasound2 libxshmfence1 libx11-xcb1
          
          # ডাউনলোড এবং সরাসরি এক্সট্রাক্ট
          curl -L https://9hits.com/downloads/v3/9hits-viewer-linux-x64.tar.bz2 | tar -xj
          
          # ফাইল পারমিশন ঠিক করা
          chmod +x ./9hits-viewer-linux-x64/9hits-viewer
          
          # সরাসরি মেইন ফোল্ডার থেকে রান
          ./9hits-viewer-linux-x64/9hits-viewer --token=08aa8c374e5713f7a572bae472c75cc4 --allow-ca --session=s1 &
          ./9hits-viewer-linux-x64/9hits-viewer --token=08aa8c374e5713f7a572bae472c75cc4 --allow-ca --session=s2
          
          # প্রসেসটি সচল রাখার জন্য ওয়েট টাইম
          sleep 340m
